apiVersion: v1
kind: Service
metadata:
  name: android-service
spec:
  selector:
    app:  
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: "5901"
    port: 5901
    targetPort: 5901
