version: "3"
services:
# Launch emulator and appium instance
  android-service:
    image: android-emulator
    build: .
    ports:
      - 4725:4725
    container_name: android
    depends_on:
      - VNC-Service
    environment:
      - APPIUM_PORT=4725
    privileged: true
    command:
      - bash
      - -c
      - | 
         ./start_emu_headed.sh
         tail -f /dev/null
    tty: true
    stdin_open: true
# Starting VNC server
  VNC-Service:
    image: android-emulator
    build: .
    ports:
      - 5900:5900
    container_name: VNC-Service
    environment: 
      VNC_PASSWORD: 123
    privileged: true
    command:
      - bash
      - -c
      - |
        ./start_vnc.sh
         tail -f /dev/null
    tty: true
    stdin_open: true
