FROM eclipse-temurin:8-jdk

ENV DEBIAN_FRONTEND noninteractive
ENV ANDROID_SDK_ROOT=/opt/android
ENV KATALON_JAVA_HOME=/opt/java/openjdk/jre
ENV PATH "$PATH:$ANDROID_SDK_ROOT/cmdline-tools/tools:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/33.0.2"
ENV DOCKER="true"
ENV DISPLAY=:1
ENV EMU=./emulator_headed_mode.sh
ENV EMU_HEADLESS=./emulator_headless_mode.sh
ENV VNC=./start_vnc.sh
ENV EMULATOR_NAME=nexus
ENV DEVICE_NAME="Nexus 6"

RUN apt-get update \
    && apt-get install -y \
        curl sudo wget unzip bzip2 libdrm-dev libxkbcommon-dev libgbm-dev libasound-dev libnss3 libxcursor1 libpulse-dev libxshmfence-dev xauth xvfb x11vnc fluxbox wmctrl libdbus-glib-1-2 \
        nodejs \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash \
    && apt-get clean \
    && rm -rf /tmp/* /var/lib/apt/lists/*

ARG ANDROID_CMD="commandlinetools-linux-8092744_latest.zip"
RUN wget https://dl.google.com/android/repository/${ANDROID_CMD} -P /tmp \
    && unzip -d $ANDROID_SDK_ROOT /tmp/$ANDROID_CMD \
    && mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/tools \
    && cd $ANDROID_SDK_ROOT/cmdline-tools \
    && mv NOTICE.txt source.properties bin lib tools/ \
    && cd $ANDROID_SDK_ROOT/cmdline-tools/tools \
    && ls \
    && yes Y | sdkmanager --licenses \
    && yes Y | sdkmanager --verbose --no_https "system-images;android-32;google_apis_playstore;x86_64" "platforms;android-32" "build-tools;33.0.2" "platform-tools"

RUN echo "no" | avdmanager --verbose create avd --force --name "${EMULATOR_NAME}" --device "${DEVICE_NAME}" --package "system-images;android-32;google_apis_playstore;x86_64"

RUN npm install -g appium@1.22.3 \
    && npm cache clean \
    && apt-get remove --purge -y npm \
    && apt-get autoremove --purge -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/lib/apt/lists/*

RUN wget https://download.katalon.com/8.6.8/Katalon_Studio_Engine_Linux_64-8.6.8.tar.gz \
    && tar -xvzf Katalon_Studio_Engine_Linux_64-8.6.8.tar.gz \
    && rm -rf Katalon_Studio_Engine_Linux_64-8.6.8.tar.gz

COPY . /

RUN chmod a+x start_vnc.sh \
    && chmod a+x emulator_headed_mode.sh \
    && chmod a+x emulator_headless_mode.sh \
    && chmod 777 vnc_portforward.sh

CMD ["/bin/bash"]
