apiVersion: v1
kind: Service
metadata:
  name: vnc-service
spec:
  selector:
    app:  
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: "5900"
    port: 5900
    targetPort: 5900